commands:
    lint:
        description: Lint
        steps:
            - run:
                command: echo Linting code.
                name: lint
    test:
        description: Test code
        steps:
            - run:
                command: echo Running test.
                name: test
executors:
    main:
        docker:
            - image: circleci/node:latest
jobs:
    lint-and-test:
        executor: main
        steps:
            - checkout
            - lint
            - test
            - run:
                command: echo "Completed linting and running tests!"
                description: Lint and then run tests.
                name: lint-and-run-tests
        working_directory: /home/circleci/project
version: 2.1
workflows:
    main-ci:
        jobs:
            - lint-and-test:
                name: lint-and-test

