executor: main
working_directory: /home/circleci/project
steps:
  - checkout
  - lint
  - test
  - run:
      name: lint-and-run-tests
      description: Lint and then run tests.
      command: |
        echo "Completed linting and running tests!"